---
- name: OSX Local Provisioner
  hosts: local
  sudo: no
  roles:
    # App Installations
    - brew
    #- defaults
    #- mas
    #- brew-cask

    # Configurations
    #- git
    #- vim
    #- xcode
    #- zsh
